name: 'David Don Hobley, Entreprenur'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.96133
title: 'David Don Hobley, Entreprenur'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d5d5'
    - '#000000'
    - '#ffffff'
    - '#808080'
    - '#555555'
  brandStrength: 0.8817830020561814
  lightness: 0.708801572676748
  saturation: 0.17145935771986842
  rhythmicContrast: 0.06245018448680639
purpose: []
