name: 'David Don Hobley, Entreprenur'
favicon: null
layout_spectrum: 0.28769389842636883
typography_spectrum: 0.1291970727033913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8817830020561814
  lightness: 0.708801572676748
  saturation: 0.17145935771986842
  rhythmicContrast: 0.06245018448680639
purpose: []
